# Project-wide Gradle settings.

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8

org.gradle.parallel=false
org.gradle.caching=false

# AndroidX package structure
android.useAndroidX=true

android.lint.abortOnError=false
android.lint.checkReleaseBuilds=false
android.overrideVersionCheck=true
kotlin.code.style=official
